# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/gollapudi.vyshnavi/Documents/Raster/tiling_example/Tiling_example_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExampleDialogBase(object):
    def setupUi(self, ExampleDialogBase):
        ExampleDialogBase.setObjectName("ExampleDialogBase")
        ExampleDialogBase.resize(438, 318)
        self.button_box = QtWidgets.QDialogButtonBox(ExampleDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.comboBox = QtWidgets.QComboBox(ExampleDialogBase)
        self.comboBox.setGeometry(QtCore.QRect(210, 40, 151, 32))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(ExampleDialogBase)
        self.label.setGeometry(QtCore.QRect(50, 50, 111, 16))
        self.label.setObjectName("label")

        self.retranslateUi(ExampleDialogBase)
        self.button_box.accepted.connect(ExampleDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(ExampleDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ExampleDialogBase)

    def retranslateUi(self, ExampleDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ExampleDialogBase.setWindowTitle(_translate("ExampleDialogBase", "ExampleTiling"))
        self.label.setText(_translate("ExampleDialogBase", "Select a file"))
